version: '3.8'

services:
  backend:
    # Construit l'image en utilisant le Dockerfile dans le répertoire actuel
    build: .
    
    # Nom du conteneur
    container_name: alpha-gaming-backend
    
    ports:
      - "8000:8000"
      
    env_file:
      - .env